jobs:
  build-linux:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Prepare coverage agent, build and test
      run: 'mvn --batch-mode jacoco:prepare-agent test jacoco:report -P prettierCheck
        -Dprettier.nodePath=node -Dprettier.npmPath=npm

        mvn --batch-mode package -Dmaven.test.skip -P prettierSkip

        '
    - continue-on-error: true
      if: github.repository_owner == 'opentripplanner'
      name: Send coverage data to codecov.io
      uses: codecov/codecov-action@v4
      with:
        files: target/site/jacoco/jacoco.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref
        == 'refs/heads/dev-1.x' || github.ref == 'refs/heads/dev-2.x')
      name: Deploy to Github Package Registry
      run: mvn --batch-mode deploy --settings maven-settings.xml -DskipTests -DGITHUB_REPOSITORY=$GITHUB_REPOSITORY
        -P prettierSkip -P deployGitHub
    timeout-minutes: 20
  build-windows:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Configure Windows Pagefile
      uses: al-cheb/configure-pagefile-action@v1.4
    - continue-on-error: true
      name: Run tests
      run: mvn --batch-mode test -P prettierSkip
    timeout-minutes: 20
  container-image:
    if: github.repository_owner == 'opentripplanner' && github.event_name == 'push'
      && (github.ref == 'refs/heads/dev-2.x' || github.ref == 'refs/heads/master')
    needs:
    - build-windows
    - build-linux
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - continue-on-error: true
      env:
        CONTAINER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        CONTAINER_REGISTRY_USER: otpbot
        CONTAINER_REPO: docker.io/opentripplanner/opentripplanner
      name: Build container image with Jib, push to Dockerhub
      run: "# we give the container two tags\n#   - \"latest\"\n#   - a string like\
        \ \"2.3_2022-12-12T21-38\"\n\nversion_with_snapshot=`mvn -q help:evaluate\
        \ -Dexpression=project.version -q -DforceStdout`\nversion=${version_with_snapshot/-SNAPSHOT/}\n\
        \nimage_version=${version}\n\n## if the Maven version contains SNAPSHOT, then\
        \ add date to tag\nif [[ $version_with_snapshot == *\"SNAPSHOT\"* ]]; then\n\
        \  image_date=`date +%Y-%m-%dT%H-%M`\n  image_version=\"${version}_${image_date}\"\
        \n  echo \"Maven version ${version_with_snapshot} contains SNAPSHOT, adding\
        \ date to container image tag\"\nfi\n\nmvn --batch-mode -P prettierSkip compile\
        \ com.google.cloud.tools:jib-maven-plugin:build -Djib.to.tags=latest,$image_version\n"
  docs:
    env:
      LOCAL_BRANCH: local-pages
      MASTER_BRANCH_VERSION: 2.5.0
      REMOTE: docs
      REMOTE_BRANCH: main
      TOKEN: ${{ secrets.CHANGELOG_TOKEN }}
    if: github.repository_owner == 'opentripplanner'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: github.event_name == 'push' && (github.ref == 'refs/heads/dev-2.x' || github.ref
        == 'refs/heads/master')
      uses: actions/checkout@v4
      with:
        fetch-depth: 1000
        token: ${{ secrets.CHANGELOG_TOKEN }}
    - continue-on-error: true
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install Python dependencies
      run: pip install -r docs/requirements.txt
    - continue-on-error: true
      if: github.event_name == 'pull_request'
      name: Build main documentation
      run: mkdocs build
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - continue-on-error: true
      name: Build GTFS GraphQL API documentation
      run: 'npm install -g @magidoc/cli@4.0.0

        magidoc generate

        '
    - continue-on-error: true
      if: github.event_name == 'push' && (github.ref == 'refs/heads/dev-2.x' || github.ref
        == 'refs/heads/master')
      name: Deploy compiled HTML to Github pages
      run: "git config --global user.name 'OTP Bot'\ngit config --global user.email\
        \ 'bot@opentripplanner.org'\n\n# mike, the versioning plugin for mkdocs, expects\
        \ there to be a local branch to push to so\n# we are cloning one here and\
        \ commit to it\n# mike has support for specifing the origin but then it tries\
        \ to rebase the _local_ gh-pages\n# branch onto the remote which fails. that's\
        \ the reason for this git hackery.\n\ngit remote add $REMOTE https://$TOKEN@github.com/opentripplanner/docs.git\
        \ \ngit fetch $REMOTE $REMOTE_BRANCH:$LOCAL_BRANCH\n\n# prefix is the root\
        \ folder where to deploy the HTML, we use 'en' to emulate the URL\n# structure\
        \ of readthedocs\n\nif [ ${{ github.ref }} = 'refs/heads/master' ]; \nthen\n\
        \  mike deploy --branch $LOCAL_BRANCH --deploy-prefix en --title=$MASTER_BRANCH_VERSION\
        \ --update-aliases v$MASTER_BRANCH_VERSION latest\nelse\n  mike deploy --branch\
        \ $LOCAL_BRANCH --deploy-prefix en dev-2.x\nfi\n\n# commit and push the GraphQL\
        \ documentation if the schema file is newer than the \n# compiled output.\
        \ it's necessary to have this check because the diffs of the magidoc tool\n\
        # this are quite large and unnecessarily increase the size of the docs repo\
        \ even when the \n# schema hasn't changed.\n# example commit: https://github.com/opentripplanner/docs/commit/45e6ddf8e4a4\n\
        \nSCHEMA_FILE_MODIFIED=`git log -n 1 --pretty=format:%ct src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls`\n\
        echo \"schema modified at ${SCHEMA_FILE_MODIFIED}\"\ngit checkout $LOCAL_BRANCH\n\
        DOCS_MODIFIED=`git log -n 1 --pretty=format:%ct api/dev-2.x/graphql-gtfs/introduction.html`\n\
        echo \"docs modified at ${DOCS_MODIFIED}\"\nif [ \"${SCHEMA_FILE_MODIFIED}\"\
        \ -gt \"${DOCS_MODIFIED}\" ]; then\n  echo \"schema.graphqls has been modified,\
        \ committing updated documentation\"\n  mkdir -p api\n  rsync -r --delete\
        \ target/magidoc/api/ api/dev-2.x/\n  git add api\n  git commit -am \"Add\
        \ Magidoc GraphQL documentation\"\nelse\n  echo \"schema.graphqls has not\
        \ been modified, not committing documentation\"\nfi\n\ngit push $REMOTE $LOCAL_BRANCH:$REMOTE_BRANCH\n"
  graphql-code-generation:
    if: github.repository_owner == 'opentripplanner'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        node-version: 16
    - continue-on-error: true
      name: Run code generator
      run: 'yarn install

        yarn generate

        '
      working-directory: src/main/java/org/opentripplanner/apis/gtfs/generated
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Compile Java code
      run: mvn --batch-mode compile -DskipTests -P prettierSkip
name: OTP CI Build
on:
  repository_dispatch:
    types: trigger-ga___cibuild.yml
