concurrency:
  group: github-push
jobs:
  debug-client:
    if: github.repository_owner == 'opentripplanner'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: github.event_name == 'push'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.CHANGELOG_TOKEN }}
    - continue-on-error: true
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - continue-on-error: true
      name: Set version
      run: echo "VERSION=`date +%Y/%m/%Y-%m-%dT%H:%M`" >> $GITHUB_ENV
    - continue-on-error: true
      name: Build debug client
      run: 'npm install

        npm run build -- --base https://cdn.jsdelivr.net/gh/opentripplanner/debug-client-assets@main/${VERSION}/

        npm run coverage

        '
      working-directory: client-next
    - continue-on-error: true
      env:
        LOCAL_BRANCH: local-assets
        REMOTE: debug-client
        REMOTE_BRANCH: main
        TOKEN: ${{ secrets.CHANGELOG_TOKEN }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/dev-2.x'
      name: Deploy compiled assets to repo
      run: "# Configure git user\ngit config --global user.name 'OTP Bot'\ngit config\
        \ --global user.email 'bot@opentripplanner.org'\n\n# Fetch the assets repo\n\
        git remote add $REMOTE https://$TOKEN@github.com/opentripplanner/debug-client-assets.git\
        \ \ngit fetch --depth=1 $REMOTE $REMOTE_BRANCH:$LOCAL_BRANCH\n\ngit checkout\
        \ $LOCAL_BRANCH\n\n\n# Copy the compiled output to a versioned folder\nmkdir\
        \ -p $VERSION\nrsync -r client-next/output/* ./$VERSION/\ngit add $VERSION\n\
        git commit -am \"Add version ${VERSION} of debug client\"\n\n# Push to assets\
        \ repo https://github.com/opentripplanner/debug-client-assets\ngit push $REMOTE\
        \ $LOCAL_BRANCH:$REMOTE_BRANCH\n\n# Switch back to the OTP code\ngit checkout\
        \ dev-2.x\ngit pull --rebase\n\nCLIENT_HTML_OUTPUT=src/client/debug-client-preview/index.html\n\
        mkdir -p src/client/debug-client-preview/\ncp client-next/output/index.html\
        \ ${CLIENT_HTML_OUTPUT}\n\n# just to debug\ncat ${CLIENT_HTML_OUTPUT}\n\n\
        git add -f ${CLIENT_HTML_OUTPUT}\ngit commit -m \"Upgrade debug client to\
        \ version ${VERSION}\"\ngit push ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git\
        \ HEAD:dev-2.x\n"
    timeout-minutes: 20
name: Debug client
on:
  repository_dispatch:
    types: trigger-ga___debug-client.yml
