jobs:
  perf-test:
    if: github.repository_owner == 'opentripplanner' && !startsWith(github.event.head_commit.message
      ,'Bump serialization version id for') && !startsWith(github.event.head_commit.message
      ,'Upgrade debug client to version')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: matrix.profile == 'core' || github.ref == 'refs/heads/dev-2.x'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      if: matrix.profile == 'core' || github.ref == 'refs/heads/dev-2.x'
      name: Set up JDK
      timeout-minutes: 5
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      if: matrix.profile == 'core' || github.ref == 'refs/heads/dev-2.x'
      name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.2
    - continue-on-error: true
      env:
        MAVEN_OPTS: -Dmaven.repo.local=/home/lenni/.m2/repository/
      if: matrix.profile == 'core' || github.ref == 'refs/heads/dev-2.x'
      name: Build jar
      run: mvn -DskipTests --batch-mode package -P prettierSkip
    - continue-on-error: true
      if: matrix.profile == 'core' || github.ref == 'refs/heads/dev-2.x'
      name: Build graph
      run: 'cp target/otp-*-SNAPSHOT-shaded.jar otp.jar

        java -Xmx32G -jar otp.jar --build --save test/performance/${{ matrix.location
        }}/

        '
    - continue-on-error: true
      env:
        MAVEN_OPTS: -Xmx50g -XX:StartFlightRecording=delay=${{ matrix.jfr-delay }},duration=30m,filename=${{
          matrix.location}}-speed-test.jfr -Dmaven.repo.local=/home/lenni/.m2/repository/
        PERFORMANCE_INFLUX_DB_PASSWORD: ${{ secrets.PERFORMANCE_INFLUX_DB_PASSWORD
          }}
        SPEEDTEST_LOCATION: ${{ matrix.location }}
      if: matrix.profile == 'core' || github.ref == 'refs/heads/dev-2.x'
      name: Run speed test
      run: 'mvn exec:java -Dexec.mainClass="org.opentripplanner.transit.speed_test.SpeedTest"
        -Dexec.classpathScope=test -Dexec.args="--dir=test/performance/${{ matrix.location
        }} -p md -n ${{ matrix.iterations }} -i 3 -0" -P prettierSkip

        '
    - continue-on-error: true
      if: matrix.profile == 'core' || github.ref == 'refs/heads/dev-2.x'
      name: Archive travel results file
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.location }}-travelSearch-results.csv
        path: test/performance/${{ matrix.location }}/travelSearch-results.csv
    - continue-on-error: true
      if: matrix.profile == 'core' || github.ref == 'refs/heads/dev-2.x'
      name: Archive Flight Recorder instrumentation file
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.location }}-flight-recorder
        path: ${{ matrix.location}}-speed-test.jfr
    strategy:
      fail-fast: false
      matrix:
        include:
        - iterations: 1
          jfr-delay: 50s
          location: germany
          profile: core
        - iterations: 4
          jfr-delay: 35s
          location: norway
          profile: core
        - iterations: 1
          jfr-delay: 50s
          location: skanetrafiken
          profile: core
        - iterations: 1
          jfr-delay: 50s
          location: hamburg
          profile: extended
        - iterations: 1
          jfr-delay: 50s
          location: baden-wuerttemberg
          profile: extended
        - iterations: 1
          jfr-delay: 50s
          location: switzerland
          profile: extended
        - iterations: 1
          jfr-delay: 20s
          location: washington-state
          profile: extended
name: Performance test
on:
  repository_dispatch:
    types: trigger-ga___performance-test.yml
