concurrency:
  group: github-push
jobs:
  changelog-entry:
    if: github.event.pull_request.merged && github.repository_owner == 'opentripplanner'
      && !contains(github.event.pull_request.labels.*.name, 'skip changelog')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.CHANGELOG_TOKEN }}
    - continue-on-error: true
      name: Configure git user
      run: 'git config --global user.name ''OTP Changelog Bot''

        git config --global user.email ''changelog-bot@opentripplanner.org''

        '
    - continue-on-error: true
      env:
        NUMBER: ${{ github.event.pull_request.number }}
        TITLE: ${{ github.event.pull_request.title }}
        URL: ${{ github.event.pull_request.html_url }}
      name: Generate changelog entry from PR information
      run: '# add a line above the one which contains AUTOMATIC_CHANGELOG_PLACEHOLDER

        ITEM="${TITLE} [#${NUMBER}](${URL})"

        TEMP_FILE=docs/Changelog.generated.md

        FILE=docs/Changelog.md

        awk "/CHANGELOG_PLACEHOLDER/{print \"- $ITEM\"}1" $FILE > $TEMP_FILE

        mv $TEMP_FILE $FILE

        git add $FILE

        git commit -m "Add changelog entry for #${NUMBER} [ci skip]"

        git pull --rebase origin dev-2.x

        git push ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git HEAD:dev-2.x

        '
  serialization-version:
    if: always() && github.event.pull_request.merged && github.repository_owner ==
      'opentripplanner' && contains(github.event.pull_request.labels.*.name, 'bump
      serialization id')
    needs:
    - changelog-entry
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install xmllint
      run: 'sudo apt-get update

        sudo apt-get install -y libxml2-utils

        '
    - continue-on-error: true
      name: Configure git user
      run: 'git config --global user.name ''OTP Serialization Version Bot''

        git config --global user.email ''serialization-version-bot@opentripplanner.org''

        '
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.CHANGELOG_TOKEN }}
    - continue-on-error: true
      env:
        NUMBER: ${{ github.event.pull_request.number }}
      name: Bump serialization version
      run: "version=`xmllint --xpath \"//*[local-name()='otp.serialization.version.id']/text()\"\
        \ pom.xml`\nbumped=$((version+1))\nsed -Ei \"s/<otp\\.serialization\\.version\\\
        .id>.*<\\/otp\\.serialization\\.version\\.id>/<otp\\.serialization\\.version\\\
        .id>${bumped}<\\/otp\\.serialization\\.version\\.id>/\" pom.xml \n\ngit add\
        \ pom.xml\ngit commit -m \"Bump serialization version id for #${NUMBER}\"\n\
        # just for safety as the Github repo is eventually consistent, therefore this\
        \ push competes with the changelog entry one\ngit pull --rebase origin dev-2.x\n\
        git push ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git HEAD:dev-2.x\n"
name: Post-merge
on:
  repository_dispatch:
    types: trigger-ga___post-merge.yml
