jobs:
  container-image:
    if: github.repository_owner == 'opentripplanner'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        CONTAINER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        CONTAINER_REGISTRY_USER: otpbot
        CONTAINER_REPO: opentripplanner/opentripplanner
      name: Delete unused container images
      run: '# remove all snapshot container images that have not been pulled for over
        a year

        # --keep-semver makes sure that any image with a x.y.z version scheme is unaffected
        by this

        pip install prune-container-repo==0.0.4

        prune-container-repo -u ${CONTAINER_REGISTRY_USER} -r ${CONTAINER_REPO} --days=365
        --keep-semver --activate

        '
name: Prune container images
on:
  repository_dispatch:
    types: trigger-ga___prune-container-images.yml
